#New properties added.
#Thu Dec 04 13:30:04 CST 2025
AmaraAnn=iamtheboss
DemoManager1=DemoManager1
ManagerEmma03=DollyIscUte11\!
Parks4321=Parkspassword
admin=admin
demoManager=demoManager
harperj=0427
